include $(APPDIR)/Make.defs

PROGNAME  = hamstrone
PRIORITY  = 100
STACKSIZE = CONFIG_DEFAULT_TASK_STACKSIZE
MODULE    = $(CONFIG_HAMSTRONE)

MAINSRC = hamstrone_main.c
CSRCS += hamster_tongue.c

include $(APPDIR)/Application.mk
