#ifndef HAMSTRONE_CONFIG_H
#define HAMSTRONE_CONFIG_H

#define HAMSTRONE_CONFIG_VALUE_SIZE 16
#define HAMSTRONE_CONFIG_VALUE_TYPE uint32_t

#define HAMSTRONE_CONFIG_SERIALPORT1_PATH "/dev/ttyS0"
#define HAMSTRONE_CONFIG_I2CPORT1_PATH "/dev/i2c1"
#define HAMSTRONE_CONFIG_I2C_ADDRESS_ITG3205 0x68
#define HAMSTRONE_CONFIG_I2C_ADDRESS_ADXL345 0x53
#define HAMSTRONE_CONFIG_I2C_ADDRESS_HMC5883L 0x1E

#define HAMSTRONE_CONFIG_ITG3205_TEMP_OUT_H 0x1B
#define HAMSTRONE_CONFIG_ITG3205_TEMP_OUT_L 0x1C

#define HAMSTRONE_CONFIG_ISSTANDALONE

#endif